### ISSUE TITLE
New debs broken on debian

### ISSUE THREAD

**Issue by theofficialgman** [ryanfortner/blockbench-arm#3]
ubuntu-latest is now ubuntu 22.04

ubuntu has an extension to apt that uses tar.zst to compress file in debs. this is used by default by dpkg when packaging debs in 22.04

this prevents all debs from installing on debian/raspbian

you need to switch to building with ubuntu-20.04 or ubuntu-18.04 which do not use this functionality when packaging debs

https://github.com/Botspot/pi-apps/actions/runs/3949187965/jobs/6760083629#step:4:865

**Comment by ryanfortner** [comment]
Thanks for letting me know. I've changed the workflow to use ubuntu 18.04 and I'm waiting on the current run to finish. Will close when it's done.

**Comment by ryanfortner** [comment]
Workflow completed successfully, closing now.
